# -----------------------------------------------------------------------------
# File        : docker-compose.yml
# Owner       : Akshay Thakare
# Created On  : 2025-04-08
# Description : MongoDB Sharding Setup using Docker Compose 
# -----------------------------------------------------------------------------

version: '3'
services:
  MongoDB:
    image: bitnami/mongodb:7.0
    container_name: mongos
    ports:
      - "27017:27017"
    command: mongos --configdb cvp/config1:27018,config2:27019,config3:27020 --port 27017 --bind_ip_all
    volumes:
      - ./data/MongoDB:/data/db
    restart: always
    networks:
      - mongodb-sharding

  config1:
    image: bitnami/mongodb:7.0
    container_name: config1
    ports:
      - "27018:27017"
    command: mongod --configsvr --replSet cvp --port 27017 --bind_ip_all
    volumes:
      - ./data/config1:/data/configdb
    restart: always
    networks:
      - mongodb-sharding

  config2:
    image: bitnami/mongodb:7.0
    container_name: config2
    ports:
      - "27019:27017"
    command: mongod --configsvr --replSet cvp --port 27017 --bind_ip_all
    volumes:
      - ./data/config2:/data/configdb
    restart: always
    networks:
      - mongodb-sharding

  config3:
    image: bitnami/mongodb:7.0
    container_name: config3
    ports:
      - "27020:27017"
    command: mongod --configsvr --replSet cvp --port 27017 --bind_ip_all
    volumes:
      - ./data/config3:/data/configdb
    restart: always
    networks:
      - mongodb-sharding

networks:
  mongodb-sharding:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.27.0.0/16"

