# -----------------------------------------------------------------------------
# File        : docker-compose.yml
# Owner       : Akshay Thakare
# Created On  : 2025-04-08
# Description : MongoDB Sharding Setup using Docker Compose
# -----------------------------------------------------------------------------

version: '3'
services:
  shard1_primary:
    image: bitnami/mongodb:7.0
    container_name: shard1_primary
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo/shard1_primary:/data/db
    restart: always
    networks:
      - mongodb-sharding

  shard2_secondary:
    image: bitnami/mongodb:7.0
    container_name: shard2_secondary
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - /data/mongo/shard2_secondary:/data/db
    restart: always
    networks:
      - mongodb-sharding

  shard3_arbiter:
    image: bitnami/mongodb:7.0
    container_name: shard3_arbiter
    command: mongod --shardsvr --replSet shard3ReplSet --port 27017 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - /data/mongo/shard3_arbiter:/data/db
    restart: always
    networks:
      - mongodb-sharding

networks:
  mongodb-sharding:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.27.0.0/16"

# -----------------------------------------------------------------------------
# File        : docker-compose.yml
# Owner       : Akshay Thakare
# Created On  : 2025-04-08
# Description : MongoDB Sharding Setup using Docker Compose
# -----------------------------------------------------------------------------
version: '3'
services:
  shard2_primary:
    image: bitnami/mongodb:7.0
    container_name: shard2_primary
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo/shard2_primary:/data/db
    restart: always
    networks:
      - mongodb-sharding

  shard3_secondary:
    image: bitnami/mongodb:7.0
    container_name: shard3_secondary
    command: mongod --shardsvr --replSet shard3ReplSet --port 27017 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - /data/mongo/shard3_secondary:/data/db
    restart: always
    networks:
      - mongodb-sharding

  shard1_arbiter:
    image: bitnami/mongodb:7.0
    container_name: shard1_arbiter
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - /data/mongo/shard1_arbiter:/data/db
    restart: always
    networks:
      - mongodb-sharding

networks:
  mongodb-sharding:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.27.0.0/16"

# -----------------------------------------------------------------------------
# File        : docker-compose.yml
# Owner       : Akshay Thakare
# Created On  : 2025-04-08
# Description : MongoDB Sharding Setup using Docker Compose
# -----------------------------------------------------------------------------
version: '3'
services:
  shard3_primary:
    image: bitnami/mongodb:7.0
    container_name: shard3_primary
    command: mongod --shardsvr --replSet shard3ReplSet --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo/shard3_primary:/data/db
    restart: always
    networks:
      - mongodb-sharding

  shard1_secondary:
    image: bitnami/mongodb:7.0
    container_name: shard1_secondary
    command: mongod --shardsvr --replSet shard1ReplSet --port 27017 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - /data/mongo/shard1_secondary:/data/db
    restart: always
    networks:
      - mongodb-sharding

  shard2_arbiter:
    image: bitnami/mongodb:7.0
    container_name: shard2_arbiter
    command: mongod --shardsvr --replSet shard2ReplSet --port 27017 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - /data/mongo/shard2_arbiter:/data/db
    restart: always
    networks:
      - mongodb-sharding

networks:
  mongodb-sharding:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.27.0.0/16"
